Activate GitHub workflow for online building of BHInsta IPA
SoCuul/SCInsta pull request #28
Opened 2024-04-18 04:24 UTC by zeuikli

Example : https://github.com/zeuikli/BHInsta/actions/runs/8732155200

Run workflow : ![CleanShot 2024-04-18 at 12 10 19@2x](https://github.com/SoCuul/BHInsta/assets/7897668/da00f2da-0ad8-4bb8-a43f-83888740111f)

Please enter the iOS SDK version and the IPA URL, then wait for the completion of the IPA build.

Build Status : ![CleanShot 2024-04-18 at 12 23 38@2x](https://github.com/SoCuul/BHInsta/assets/7897668/703facaf-bb78-4f95-9e25-eb061b493d4c)

Confirm that the IPA file can be installed via eSign, but note that the image download feature is still not functioning properly.

2024-04-19 21:54 UTC, SoCuul commented on .github/workflows/buildapp.yml
> +          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/arichornlover/sdks/
If possible it'd be great to download the SDKs from https://github.com/xybp888/iOS-SDKs

2024-04-19 21:55 UTC, SoCuul commented on .github/workflows/buildapp.yml
> +        run: |
If this could be made to run the build script instead that would be great.
Having duplicated building code could cause confusions in the future.

2024-04-19 21:57 UTC, SoCuul commented on .github/workflows/buildapp.yml
> +# Original idea by @ISnackable. Thanks to him for handling the hardest parts!
Maybe credit the uYouEnhanced script up here in a comment as well, since they made this base script haha.

2024-04-20 06:33 UTC, zeuikli commented
After the review, you can merge your commit into the main branch.

2024-04-20 08:16 UTC, zeuikli commented
Update build.sh to fix the issue of IPA file not being found.

Added script commands to install pyzule.
#Install pyzule
bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"

Modified the build.sh script by replacing certain instructions originally designated for BHInsta with those intended for SCInsta.

You can review my latest PR to verify these changes.

2024-04-20 08:57 UTC, SoCuul commented
> Update build.sh to fix the issue of IPA file not being found.
> 
> Added script commands to install pyzule. #Install pyzule bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"
> 
> Modified the build.sh script by replacing certain instructions originally designated for BHInsta with those intended for SCInsta.
> 
> You can review my latest PR to verify these changes.

It's super inefficient to install pyzule each time someone tries to build it, as they only need to install it once.

Could you just add it as another step in the buildapp workflow?

Also, just leave build.sh as it is in the main branch for now, as I want to keep the functionality the same atm.

2024-04-20 09:06 UTC, SoCuul requested changes
All that needs to be changed is moving the pyzule stuff to a build step and reverting the changes in `build.sh`. The script should run fine if in the workflow step it cds into the folder, as all the paths in the shell script are relative to the current directory.

2024-04-22 03:35 UTC, zeuikli commented
Initially, you can proceed with the merge, but it's imperative to ensure that the "pyzule" tool is installed using GitHub Actions to facilitate the building of the IPA.

2024-04-22 20:37 UTC, SoCuul commented
> Initially, you can proceed with the merge, but it's imperative to ensure that the "pyzule" tool is installed using GitHub Actions to facilitate the building of the IPA.

I do not feel comfortable merging this into the main branch in its current state, as it would cause confusion for users who do not understand why the workflow fails on their end.

2024-05-13 01:21 UTC, SoCuul commented
@zeuikli If you're working on this, what do you think about adding a dropdown in the workflow settings to select between sideloaded ipa, rootless and rootful

2024-06-20 04:17 UTC, zeuikli commented
@SoCuul I have already updated the Github workflow and package dependencies to enable building IPA and deb files.
You can review my pull request, but since your settings are for local builds, I recommend not merging my PR into the main branch. Instead, you can create another branch for GitHub Actions use cases.

2024-06-25 06:37 UTC, SoCuul commented
> @SoCuul I have already updated the Github workflow and package dependencies to enable building IPA and deb files. You can review my pull request, but since your settings are for local builds, I recommend not merging my PR into the main branch. Instead, you can create another branch for GitHub Actions use cases.

Thank you so much for your work! I'll take a look at the PR when I can.

2024-08-06 23:38 UTC, ic3dlem0n commented
W zeuiki now sideloading this won't more complicated than it already is

2024-08-14 05:39 UTC, SoCuul commented
I still plan on implementing this when I can find the time. Kinda burned out rn from working on this atm.

2024-09-23 06:23 UTC, merged

2024-09-23 06:24 UTC, SoCuul commented
@zeuikli Thank you so much for your work on this! Incredibly appreciated by me 😄